[package]
name = "sentry_tunnel"
version = "1.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="sentry_tunnel"
path="src/main.rs"

[lib]
name="sentry_tunnel"

[dependencies]
gotham = "0.7.0"
futures-util = "0.3.14"
serde = "1.0"
serde_json = "1.0"
isahc = {version = "1.5", features = ["static-ssl", "http2", "static-curl", "text-decoding"], default_features=false}
anyhow = "1.0"
envmnt = "0.10"
log = "0.4"
stderrlog = "0.6"
mime = "0.3"
url = "2.2"
sentry-types = "0.34.0"
tokio = { version = "1.11.0", features = ["full"] }


[dev-dependencies]
httpmock = "0.7"
